### ISSUE TITLE
Dodać informację o formie prowadzonych zajęć stacjonarnie/zdalnie

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#100]

**Comment by sulmar** [comment]
Dodać informację w formie ikony + tekst `zdalnie/stacjonarnie`
![teacher](https://github.com/sulmar/sulmar-homepage/assets/779025/3d5a15bf-78b1-492a-a7e9-c3bad1b11532)

**Comment by sulmar** [comment]
Powinna znaleźć się w sekcji:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/3a5ac650-87f6-4b9e-a686-13e2d041c4d9)

**Comment by sulmar** [comment]
Proponuję całkowicie po prawej. Skrajne elementy są lepiej widoczne.

**Comment by jszufa** [comment]
chyba faktycznie lepiej 4 ikony, bo 5 to trochę dużo:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/f0297a10-ae00-4e85-b4f6-87602733097a)

**Comment by sulmar** [comment]
Tego się obawiałem. Usuńmy ilość lekcji.

**Comment by jszufa** [comment]
zastanawiam się też czy nie będzie bardziej spójne z nieco inną ikoną (ale z tego samego setu co reszta). 
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/c85403f7-a750-41db-975c-eb40ea3ecb9b)

**Comment by sulmar** [comment]
OK, ale usuń ilość lekcji, a czas trwania szkolenia zostaw :)

**Comment by sulmar** [comment]
Po usunięciu ilości lekcji możemy anulować #66 i #102

**Comment by jszufa** [comment]
Ups! Poprawione
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/b6176805-9747-46fa-9f79-741cf7bb9155)

**Comment by sulmar** [comment]
Teraz jest super! Wszystkie najbardziej istotne informacje pod ręką. Prosto i czytelnie.
