### ISSUE TITLE
Podmienić obraz na Hero

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#101]
Kupić obrazek aby nie pojawiał się znak wodny:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/a35b3af5-4d66-4d44-8e88-1254eef234a4)

**Comment by sulmar** [comment]
Link do zdjęcia: https://www.istockphoto.com/pl/wektor/programista-pisze-j%C4%99zyk-komputerowy-gm1440001165-480104877

**Comment by sulmar** [comment]
Kupiłem.

**Comment by sulmar** [comment]
Możesz go teraz podmienić na głównej stronie.

**Comment by jszufa** [comment]
no i jest pięknie:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/9a5bdba5-9e5d-4f85-86b4-7375546cad1a)

Dodałem od razu responsywność na mniejsze ekrany.
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/30dd1b2e-7e01-4452-88bc-b567dbc45543)
