### ISSUE TITLE
Szablon szkolenia - lista tematów - ponumerować pierwszy poziom

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#11]
Ponumerować pierwszy poziom
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/d77cfb16-4ea2-4fc3-ab08-51cc100a8fb5)

za pomocą tagów `<ol>...</ol>`
```html
<ol>
  <li>Introduction
    <ul>
      <li>Lesson1</li>
      <li>Lesson2</li>
    </ul>
  </li>
  <li>XAML
    <ul>
      <li>Lesson1</li>
    </ul>
  </li>
</ol>

```

**Comment by jszufa** [comment]
Dodałem numerację w czystym css :)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/84b0f4e9-6afe-48e4-a92d-615994a2c59f)

Lista na razie została taka jaka była w md (czyli ul). Czy tak ma zostać, czy dodajemy numerację w plikach md?
