### ISSUE TITLE
Logo GitHub jest niewidoczne w trybie dark

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#112]

**Comment by sulmar** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/606596cb-0956-4730-84d7-f558b9558e1f)

**Comment by jszufa** [comment]
Poprawiłem:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/097f7fb2-015b-4cb7-8835-9afe0c3da3de)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/b094abfc-157c-448a-b677-4e12c151354a)
