### ISSUE TITLE
Folder testimonials - dodać nowe opinie do plików md

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#14]

**Comment by sulmar** [comment]
"Jestem zadowolony z przeprowadzonego szkolenia.
Bardzo dobry kontakt, duża ilość materiałów dydaktycznych. Szkolenie odbyło się w miłej atmosferze.
**Największą zaletą w przeprowadzonym szkoleniu była ogromna ilość praktycznych ćwiczeń, które pomogły w zrozumieniu treści**. Polecam serdecznie."

Sebastian Bąk 
DSM-Firmenich
Podstawy języka SQL

**Comment by sulmar** [comment]
"Szkolenie zostało przeprowadzone w profesjonalny sposób, zachęcający do aktywnego udziału. Prowadzący potrafi efektywnie przekazać wiedzę oraz elastycznie dopasować kierunek szkolenia do wymagań i oczekiwań uczestników." 

Tomasz Tyszka
Grupa Santander
Szkolenie Tworzenie usług sieciowych WebApi

**Comment by sulmar** [comment]
"Jedno z najlepiej zrealizowanych szkoleń w jakim brałam udział. Prowadził je świetny trener, posiadający ogromną wiedzę oraz potrafiący przekazać ją w sposób jasny i przejrzysty. Odpowiadał na każde z pytań i wątpliwości. Tworzył przyjazną atmosferę na zajęciach. Prowadził je w sposób ciekawy i angażujący uczestników do wykonywania ćwiczeń. Polecam to szkolenie wszystkim rozpoczynającym przygodę z programowaniem w C#." 
Agnieszka Kudlińska
Okręgowy Inspektorat Pracy w Poznaniu
Podstawy języka C#

**Comment by jszufa** [comment]
Dodane :)
