### ISSUE TITLE
Szablon szkolenia - program szkolenia - zmienić na normalną czcionkę

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#2]
Punkty agendy powinny być czcionką Normal a tylko grupy jako **Bold**
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/c060f65b-232e-43b7-91d5-d114200ef7d5)

Tak jak tutaj:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/2eaa2843-232d-49c5-884d-49b7ae61944f)

**Comment by jszufa** [comment]
Czy stylowanie takie jak na obrazku powyżej, czy takie proste jak poniżej?
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/da73b4b2-9c9f-4026-9b04-d10cb4d5caad)

**Comment by sulmar** [comment]
Podoba mi się punktatory w postaci kółek bo "niby" do odhaczenia. Czcionka regular a nie bold.

**Comment by sulmar** [comment]
Teraz ładniej.
