### ISSUE TITLE
Dodać w sekcji Kontakt adres firmowy

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#29]
```
ul. Erazma Ciołka 10 lok. 229
01-402 Warszawa
```

**Comment by jszufa** [comment]
zastanawiam się czy nie wystarczy sama informacja na mapce: 
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/77886a2b-e5c6-472c-8b3f-e12eca58c71d)

czy też dodawać specjalny napis: 
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/edff9a6b-6171-4943-bafe-a4b4ac73ba06)

**Comment by sulmar** [comment]
Sądzę, że poza mapą powinien być adres, może później NIP.

**Comment by jszufa** [comment]
dzięki, to zostawiam tak:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/c3fa63dc-a459-4c1d-9164-de06b27d8dac)
