### ISSUE TITLE
Szablon szkolenia sekcję Czego się nauczysz

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#3]
Przenieść sekcję **Czego się nauczysz** 
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/5068da44-1230-4633-a345-e169089b7244)

do takiej formy:

![image](https://github.com/sulmar/sulmar-homepage/assets/779025/a6c82477-419d-48b9-97d4-4b662ca37aba)

Czyli:
- [x] proste haczyki
- [x] usunąć zdjęcie
- [x] układ 2 kolumnowy
- [x] delikatne tło (opacity?) w kolorze kategorii

**Comment by jszufa** [comment]
Mamy teraz coś takiego:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/37c16c9f-c07e-4aa6-9f97-d6fd63ec381f)
