### ISSUE TITLE
zmienić ikonografikę w karuzeli opini

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#39]
Na taką: https://nicepage.com/pl/html-templates/preview/cytat-z-pomaranczowym-tlem-43282?device=desktop

**Comment by jszufa** [comment]
dodałem -  w tym momencie wygląda to tak:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/af2ea16f-63a2-4add-9e9d-aea5c6199ef3)

**Comment by sulmar** [comment]
Bardzo ładnie.
