### ISSUE TITLE
Szablon szkolenia - dodać informacje o poziomie, ilości lekcji, godzin i certyfikacie

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#4]
W takim stylu:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/b037e0c8-9d86-4890-b852-7f9305f4c340)

Dodać:
- [x] poziom
- [x] ilość lekcji
- [x] ilość godzin
- [x] certyfikat ukończenia

Ikonki mogą przesłać.

**Comment by jszufa** [comment]
Zrobiłem 2 wersje, która Ci się bardziej podoba?
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/1341be26-acb0-4fc5-ad85-39465ade15d6)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/a09433fd-5764-45ee-ad0b-cef3913590c1)

Ikonka poziomu na pewno do zmiany - jeśli masz gotową, to byłbym bardzo wdzięczny :)

**Comment by sulmar** [comment]
Głosuję za pierwszą wersją +1
Ale zapytam jeszcze grafika.

**Comment by sulmar** [comment]
Pobrałem ze strony https://www.educative.io/courses/building-cross-platform-applications-with-dot-net-maui

- Początkujący
```
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="9" y="7" width="2.5" height="10" fill="#8F8F99"></rect><rect x="3.5" y="11" width="2.5" height="6" fill="#FAFAFA"></rect><rect x="14.5" y="3" width="2.5" height="14" fill="#8F8F99"></rect></svg>
```

- Średnio-zaawansowany
```
<svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><rect x="9" y="7" width="2.5" height="10" fill="#FAFAFA"></rect><rect x="3.5" y="11" width="2.5" height="6" fill="#FAFAFA"></rect><rect x="14.5" y="3" width="2.5" height="14" fill="#8F8F99"></rect></svg>
```
