### ISSUE TITLE
Dodać opinię

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#40]
_Szkolenie z Crystal Reports było bardzo interesujące. Podobała mi się zwłaszcza forma pracy na realnych danych z bazy firmy, dzięki czemu mogliśmy uczyć się na przykładach i rozwiązywać nasze prawdziwe problemy. To, moim zdaniem, znacznie ciekawsze podejście niż nauka na przykładach bardziej abstrakcyjnych i książkowych. Polecam._
Jacek Leśniewicz
Formika Sp. z o.o.

Szkolenie: Crystal Reports

**Comment by jszufa** [comment]
dodałem opinię :)
