### ISSUE TITLE
Dodać sekcję opinię pod szkoleniem 

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#42]
Opinie powinny dotyczyć tylko tego szkolenia - należy przefiltrować opinie po kategorii szkolenia.

**Comment by jszufa** [comment]
Dodałem.
W tym momencie filtruję jeśli tytuł szkolenia zawiera kategorię opinii. Czyli np. "Crystal Reports dla początkujących" łapie opinie z kategorią "Crystal Reports": 
~~~
props.currentCourse.includes(page.frontmatter.category)
~~~

W tym momencie kurs Crystal reports dla początkujących łapie tylko 2 opinie, i Wzorce projektowe w C# łapią 1 opinię.
Widzę też potencjalny problem z kategoriami takimi jak: WPF MVVM. Tutaj jest skrótowo, a tytuł szkolenia pewnie będzie brzmiał inaczej. Pytanie, czy nie dodać jakiegoś dodatkowego typu do opinii (albo bardziej ogólnego np. "dotnet", albo pozwalającego na pewną identyfikację np. slug: "razor-pages". Co o tym myślisz?

**Comment by jszufa** [comment]
Super, to będzie dobrze działać.
Czy wiesz już może, jak mogą wyglądać slugi do tych kursów? (Są opinie, ale nie ma jeszcze odpowiednich krusów):
- [ ] WPF MVVM
- [ ] Podstawy języka SQL
- [ ] Tworzenie usług sieciowych WebApi
- [ ] Podstawy języka C#

**Comment by sulmar** [comment]
slugi:
- WPF MVVM - `wpf`
- Podstawy języka SQL `sql`
- Podstawy języka C# `csharp`

- Tworzenie usług sieciowych WebApi - to szkolenie poleci do archiwum

**Comment by jszufa** [comment]
Dzięki - dodałem slugi.
