### ISSUE TITLE
Kolorystyka dla maui i blazor

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#43]
Zastanawiam się też nad kolorystyką dla maui i blazor (czy zostawić może dla blazora taki sam kolor jak dla dotnet?).

![screencapture-localhost-8080-sulmar-homepage-2024-03-27-13_23_52](https://github.com/sulmar/sulmar-homepage/assets/118739912/e50f7779-9883-4a2c-b23a-c39a9bd83d88)

**Comment by sulmar** [comment]
Spróbuj maui i blazor zrobić jako fiolet bo te technologie się zazębiają.

**Comment by jszufa** [comment]
Dzięki - zrobione :)
