### ISSUE TITLE
Sortowanie szkoleń

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#45]
Czy masz pomysł na sortowanie kafelków? Czy np. wyświetlać je grupami, albo według popularności kursów?

**Comment by sulmar** [comment]
Tak, proponuję do metadanych dodać wagę (_weight_) i wg tego sortować:
```
---
title: "Page Title"
weight: 10
---
```

**Comment by jszufa** [comment]
Dzięki, zrobione :)
