### ISSUE TITLE
Poprawić wygląd sekcji Podobnych Kursów

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#48]

**Comment by jszufa** [comment]
Zrobiłem analogicznie jak na stronie głównej.
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/75315ddc-a162-4e9c-a75a-405ca1cdf037)

**Comment by sulmar** [comment]
- [ ] Zmień nazwę "Podobne szkolenia" na "Powiązane szkolenia"
