### ISSUE TITLE
Redis 7.0 dla programistów - zmienić opis

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#5]
Skąd pobierany jest opis szkolenia?

Chciałem podmienić aktualny opis Redisa na taki:

_Redis to magazyn danych o strukturze klucza i wartości typu open source, przechowywany w pamięci, należący do kategorii baz danych NoSQL. Redis może być używany jako wysokowydajna pamięć podręczna w pamięci, broker komunikatów i silnik przesyłania strumieniowego. Dzięki temu kursowi zdobędziesz umiejętność tworzenia wydajnych aplikacji przy użyciu Redis i .NET._

**Comment by jszufa** [comment]
Póki co był wklejony na sztywno, ale teraz już jest w nagłówku plików md.
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/c996f449-963c-4235-9711-de21db46fd47)

Zmieniłem na aktualny.
