### ISSUE TITLE
Szablon szkolenia - dodać informację, że jest to szkic i pomijać go w wyświetlaniu na stronie

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#51]
Umożliwi to wygodne edytowanie nowych szkoleń zanim zostaną opublikowane. Poza tym umożliwią archiwizowanie starych szkoleń bez potrzeby ich usuwania.

- [x] Dodać do metadanych słowo kluczowe `draft`

```
---
title: "Page Title"
draft: true
---
```

- [x] filtrować listę kursów na głównej stronie 
- [x] filtrować kursy powiązane

**Comment by jszufa** [comment]
Zrobione, filtruje kursy na stronie głównej i kursy powiązane.
