### ISSUE TITLE
Aktualizacja kursów - tagline'y

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#57]
Dodać tagline'y do: 
- [x] maui.md
- [x] ml-net.md,
- [x] razor-pages.md
- [x] unit-testing.md

~~~
tagline: Lorem ipsum? Lorem ipsum dolor.
~~~

**Comment by sulmar** [comment]
- unit-testinng - _Testuj szybko, prosto i bezbłędnie_

**Comment by sulmar** [comment]
- ml-net.md _Naucz maszynę. Naucz siebie._

**Comment by sulmar** [comment]
MAUI - "bądź zwinny i mobilny"

**Comment by sulmar** [comment]
- razor-pages - _Strony webowe ostre jak brzytwa_

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/47467c8b-ab52-4bb6-8012-5718741055da)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/19ea6084-8034-44f0-ae05-19a06a0540f2)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/d2b904a9-93c0-4c26-9626-3062c449d084)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/175bd03c-c7e2-4262-b715-d2173b1cb33c)
