### ISSUE TITLE
Zmodyfikować sekcję o mnie

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#59]
Na wzór:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/4c559d79-b009-4981-b7b3-736fec83b5d0)

- [x] Dodać nagłówek
- [x] Dodać opis
- [x] Dodać zdjęcie
- [x] Dodać region w liczbach

**Comment by jszufa** [comment]
Aktualnie wygląda to tak:
![screencapture-localhost-8080-sulmar-homepage-2024-03-29-12_03_29](https://github.com/sulmar/sulmar-homepage/assets/118739912/5fa2a7ec-a07e-4477-871b-6990a91927ec)

**Comment by sulmar** [comment]
Coraz ciekawiej. Może tekst pod zdjęciem?

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/bbdddda6-7f15-4383-be35-e36b2912d82b)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/aaf37ae7-4ece-4a1a-9c2d-989da7655541)

**Comment by jszufa** [comment]
Chyba, że w ogóle tak :) 
![screencapture-localhost-8080-sulmar-homepage-2024-03-29-12_24_21](https://github.com/sulmar/sulmar-homepage/assets/118739912/6e6155c9-febd-494d-ba6c-3f53de37cfe7)

**Comment by jszufa** [comment]
to tak zostawiam :)
