### ISSUE TITLE
Zmienić pozycję slajdów Karuzela Opinii

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#62]
Żeby uniknąć takiego efektu:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/b22cde0e-5ac4-4d50-b25f-191593633340)

- [x] Zmienić pozycję startową na większych rozdzielczościach
- [x] spróbować wyłączyć autoplay, jeśli jest mało slajdów

**Comment by sulmar** [comment]
Może wycentrować?

**Comment by jszufa** [comment]
Tak - już poprawiłem : )
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/08af0bdd-61e3-4b3f-9a4e-afaa667b7f2c)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/dc806092-9af1-4410-938c-9466058672ba)

**Comment by sulmar** [comment]
Świetnie. Czy możesz usunąć gradient? Albo moze całkowicie ludka w imię prostoty.
