### ISSUE TITLE
Strona główna - opinie - dodać strzałki lewo prawo do przewijania

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#7]

**Comment by jszufa** [comment]
w tym momencie strzałki wyglądają tak - pytanie czy zostawiamy?
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/9f886b35-e447-4ed5-9785-4614a3ead54e)

**Comment by jszufa** [comment]
Zmieniłem na takie - myślę, że będą lepsze:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/01d00072-8daa-4596-a47a-fa96a0817693)
