### ISSUE TITLE
Dodać odpowiedni tekst do nagłówka listy kursów

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#81]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/40adfadc-a437-4449-a1e1-0a0154372578)

**Comment by sulmar** [comment]
_Wrzuć wyższy bieg. Zamiast slajdów kodowanie na żywo. Starannie dobrane przykłady abyś mógł zdobytą wiedzę zastosować w praktyce. Czysty kod i doświadczenie w miłej postaci._

**Comment by sulmar** [comment]
_Wrzuć wyższy bieg. Zamiast slajdów kodowanie na żywo. Starannie dobrany materiał i przykłady abyś mógł zdobytą wiedzę zastosować w praktyce. Czysty kod i doświadczenie w miłej postaci._

**Comment by jszufa** [comment]
Super :) Czy "Wrzuć wyższy bieg" jako nagłówek zamiast "Szlifuj umiejętności programistyczne"?

**Comment by sulmar** [comment]
Tak, spróbujmy.

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/60a28695-bac5-4990-b990-9359b22d4dc2)
