### ISSUE TITLE
Maksymalna szerokość kontenerów

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#82]
Ustawiłem maksymalną szerokość rezultatów, opisu i programu kursu, na 1200px, żeby się treść nie rozlewała na dużych ekranach.
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/24ef1924-d26d-4717-bc5b-6334bf13a4fb)

**Comment by sulmar** [comment]
Świetnie, bo mam szeroki monitor i zauważyłem już wcześniej, że źle się czyta.
