### ISSUE TITLE
Poprawić responsywność sekcji hero kursu

### ISSUE THREAD

**Issue by jszufa** [sulmar/sulmar-homepage#83]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/8b10a0e3-3a91-4c5b-b79c-27c9398f753d)

**Comment by sulmar** [comment]
Będziemy obrazek wyświetlać pod spodem czy całkowicie go ukrywać?

**Comment by jszufa** [comment]
Myślałem, żeby pod spodem, ale być może ukrywanie okaże się bardziej estetyczne.

**Comment by sulmar** [comment]
Z drugiej strony jak to dobrze działa to jest ciekawiej:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/4cff9ac3-256a-4cec-a7ff-5d5509093e3b)

**Comment by sulmar** [comment]
Potwierdzam wcześniejszy wpis - na mniejszym rozmiarze obrazek powinien pojawić się pod tytułem.

**Comment by jszufa** [comment]
Zrobione :)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/b8eca7cc-4ef0-4caf-bd49-52d71ffc7a41)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/87438f63-854a-43cc-822a-3dd0e3b4471a)

Kursy, które nie mają obrazka (albo mają ustawione image: false) wyświetlają się tak:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/9ebf5d11-0d7a-400b-916f-28940528e929)

**Comment by jszufa** [comment]
Trzeba będzie tylko sprawdzić, czy te style dobrze działają gdyby pojawiły się obrazki (kawałki kodu) w nieco innych proporcjach. Teraz jest 4:3..
