### ISSUE TITLE
Usunąć gradient w opiniach

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#85]
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/7e6578c9-7b24-43d5-a157-6b10295d0c0e)
Chyba sam niebieski wystarczy.

**Comment by sulmar** [comment]
A może całkowicie pozbyć się ikony celem uproszczenia?

**Comment by sulmar** [comment]
Proponuję do _Uczestnik_ dopisać _Uczestnik szkolenia_

**Comment by jszufa** [comment]
Zrobione:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/08dd9eed-8c87-47fa-bd60-3dc0d34f8350)

Który wariant bardziej Ci się podoba - z ikonami, czy bez?
Mi chyba ten z ikonami, ale oczywiście, super by było, gdyby było kilka zdjęć.

**Comment by sulmar** [comment]
Wersja z ikonami.
