### ISSUE TITLE
Szablon szkolenia - poprawić formatowanie w trybie ciemnym

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#86]
Poprawić kolor tekstu w nagłówkach na biały.
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/e319e57c-c616-41d4-9b8f-4b6991815ebb)

**Comment by sulmar** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/5daac977-e22b-4fde-8d0d-3c52fa6cfb50)

**Comment by jszufa** [comment]
poprawiłem:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/c57871f8-a3b0-4412-b429-9251211d9f9d)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/97e35189-cab5-4326-9b5b-f43597a5e762)
