### ISSUE TITLE
Poprawić kolory opinii w trybie ciemnym

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#87]
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/daf31063-f741-4f89-b538-ae4041d3f990)

**Comment by jszufa** [comment]
Poprawiłem:
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/786a0384-7358-4ebf-9eb1-ee8bc661e04b)
