### ISSUE TITLE
Kontakt - formularz kontaktowy wyrównać względem adresu

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#88]
Obecnie w układzie mobilnym jest to przesunięte względem siebie:
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/12ae8b24-1c76-4506-8b3c-23d2126be2d2)

Drobiazg ale zauważyłem ;-)

**Comment by sulmar** [comment]
Należy formularz wyrównać do lewej aby był zgodny z mapą.

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/6b395255-c715-4072-8b7e-99773f6ce598)

Zrobione.
