### ISSUE TITLE
Utrudnione wyszukiwanie na urządzeniu mobilnym

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#89]
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/1a418832-9ca6-43fd-abb2-b0f4366e7254)

**Comment by sulmar** [comment]
Proponuję aby po kliknięciu lupy pojawiało się pole wyszukiwania pod spodem logo.

**Comment by jszufa** [comment]
Spojrzałem, jak zrobili oryginalnie w vuepress 2 i zrobiłem analogicznie. Zrobiłem deployment - także możesz sprawdzić czy Ci to odpowiada.
Na małych rozdzielczościach znika ikonka dark-mode.
Na bardzo małych ekranach pole najeżdża na logo, ale "z zapasem" tła.
Daj proszę znać, co myślisz :)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/e3d747b6-5496-41e3-8aef-0414c64caaea)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/64948933-a370-416e-8ce8-aede36c1dae9)

**Comment by sulmar** [comment]
A może niech znika logo? Jak coś szukasz to logo nie ma znaczenia.

**Comment by jszufa** [comment]
Ok, tak zrobiłem.
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/25abb569-a9ab-460d-8de4-37932bc29150)

**Comment by sulmar** [comment]
Świetnie, a czy możesz poszerzyć pole wyszukiwania na całą szerokość aż do hamburger menu?
![image](https://github.com/sulmar/sulmar-homepage/assets/779025/9bc67dd8-8eab-4895-b4a4-97718f395bec)

**Comment by jszufa** [comment]
Zrobione :)
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/2acd733a-ccdf-4f50-91b7-732b097579e3)
