### ISSUE TITLE
Ustawić Title

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#90]
Ustawić tytuł strony na Sulmar - szkolenia

**Comment by jszufa** [comment]
Zrobione :) Czy chcesz ustawić jakiś konretny favicon?
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/baf656b5-9a12-4d28-8db2-86aa65f6cf34)

**Comment by sulmar** [comment]
Może bardziej szczegółowo _Szkolenia dla programistów_.

**Comment by sulmar** [comment]
> Czy chcesz ustawić jakiś konretny favicon?

Tak. Prześlę ci ikonkę która była do tej pory.

**Comment by sulmar** [comment]
Wątek dotyczący favicon przeniosłem do #93

**Comment by jszufa** [comment]
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/ce42ef87-6fb1-47dd-8b24-34b60da8b66c)
