### ISSUE TITLE
Ustawić favicon

### ISSUE THREAD

**Issue by sulmar** [sulmar/sulmar-homepage#93]
![sulmar-big](https://github.com/sulmar/sulmar-homepage/assets/779025/53928965-803a-469f-b3c0-7c3b8e04ad0e)
![sulmar](https://github.com/sulmar/sulmar-homepage/assets/779025/51cb09a4-5a78-4ec9-97fb-a4c79cde72d6)

**Comment by jszufa** [comment]
favicon dodany 
![image](https://github.com/sulmar/sulmar-homepage/assets/118739912/b10368fe-f776-4658-a1af-ea8c9c095df3)
